.\"
.\" Copyright (C) 2007 Sven Arvidsson <sa@whiz.se>
.\" Copyright (C) 2019 Arnaud Bonatti <arnaud.bonatti@gmail.com>
.\"
.\" GNOME Tetravex is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" GNOME Tetravex is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License along
.\" with this GNOME Tetravex.  If not, see <https://www.gnu.org/licenses/>.
.\"
.TH gnome-tetravex-cli 6 "2019\-11\-07" "GNOME"
.SH NAME
Tetravex \- A simple puzzle game to play in CLI
.SH SYNOPSIS
.B gnome-tetravex-cli
.RI [ OPTION... ]
.RI [ COMMAND ]
.SH DESCRIPTION
GNOME Tetravex is a simple puzzle where pieces must be positioned so
that the same numbers are touching each other.
.br
.br
This is a CLI program; see also `gnome-tetravex` for the Gtk application.
.SH OPTIONS
.TP
.B \-c, \-\-colors=NUMBER
Set number of colors (2-10)
.TP
.B \-s, \-\-size=SIZE
Set size of board (2-6)
.TP
.B \-v, \-\-version
Print release version and exit
.P
.SH COMMAND
.TP
.B A1b2
Invert two tiles, the one in A1, and the one in b2.
.br
An uppercase targets a tile from the initial board.
.br
A lowercase targets a tile in the left/final board.
.br
Digits specify the rows of the two tiles to invert.
.br
.br
.PP
.B (nothing)
.br
.B status
.br
.B show
.RS 7
Show the current puzzle.
.RE
.TP
.B new
Create a new puzzle; for changing size, use --size.
.TP
.B solve
Give up with current puzzle, and view the solution.
.PP
.B finish
.br
.B end
.RS 7
Finish current puzzle, automatically. Works for puzzles solved right or if one tile left.
.RE
.PP
.B up,\ \ \ \ l-up
.br
.B down,\ \ l-down
.br
.B left,\ \ l-left
.br
.B right,\ l-right
.RS 7
Move all left-board tiles up/down/left/right by one.
.RE
.PP
.B r-up
.br
.B r-down
.br
.B r-left
.br
.B r-right
.RS 7
Move all right-board tiles up/down/left/right by one.
.RE
.SH AUTHORS
.B gnome-tetravex-cli
was written by Arnaud Bonatti.
