name: gnome-tetravex
version: git
summary: Reorder tiles to fit a square
description: |
  Each square piece has a number on each side. Position the pieces on the left
  side of the board so that the same numbers are next to each other. If the
  numbers don't match, you can't put the piece there. Move quickly: you're
  being timed!

  You can make the game easier or harder by changing the size of the board.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core18

slots:
  # for GtkApplication registration
  gnome-tetravex:
    interface: dbus
    bus: session
    name: org.gnome.Tetravex

apps:
  gnome-tetravex:
    command: usr/bin/gnome-tetravex
    extensions: [gnome-3-28]
    plugs:
      - gsettings
    desktop: usr/share/applications/org.gnome.Tetravex.desktop

parts:
  gnome-tetravex:
    source: .
    source-type: git
    override-build: |
      sed -i.bak -e 's|Icon=org.gnome.Tetravex$|Icon=${SNAP}/meta/gui/org.gnome.Tetravex.png|g' data/org.gnome.Tetravex.desktop.in
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/48x48/org.gnome.Tetravex.png $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../install/usr/share/applications/org.gnome.Tetravex.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    plugin: meson
    meson-parameters: [--prefix=/usr]
    organize:
      snap/gnome-tetravex/current/usr: usr
    build-packages:
      - gettext
      - itstool
      - libglib2.0-dev
      - libgtk-3-dev
      - valac
