name: gnome-tetravex
version: git
summary: Reorder tiles to fit a square
description: |
  Each square piece has a number on each side. Position the pieces on the left
  side of the board so that the same numbers are next to each other. If the
  numbers don't match, you can't put the piece there. Move quickly: you're
  being timed!

  You can make the game easier or harder by changing the size of the board.     

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict

plugs:
  gnome-3-26-1604:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-26-1604
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes

slots:
  # for GtkApplication registration
  gnome-tetravex:
    interface: dbus
    bus: session
    name: org.gnome.tetravex

apps:
  gnome-tetravex:
    command: desktop-launch gnome-tetravex
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - unity7
      - wayland
    desktop: usr/share/applications/gnome-tetravex.desktop
    environment:
      PATH: $SNAP/usr/games:$PATH

parts:
  gnome-tetravex:
    build-attributes: [no-system-libraries]
    after: [desktop-gnome-platform]
    source: .
    source-type: git
    override-build: |
      sed -i.bak -e 's|Icon=gnome-tetravex$|Icon=${SNAP}/meta/gui/gnome-tetravex.png|g' data/gnome-tetravex.desktop.in
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/48x48/gnome-tetravex.png $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp data/gnome-tetravex.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    plugin: autotools
    configflags: [--prefix=/snap/gnome-tetravex/current/usr, --bindir=/snap/gnome-tetravex/current/usr/games]
    organize:
      snap/gnome-tetravex/current/usr: usr
    build-packages:
      - appstream-util
      - gnome-pkg-tools
      - intltool
      - libglib2.0-dev
      - libgtk-3-dev
      - valac
      - yelp-tools

